### ISSUE TITLE
When scrolling down the line is above the cursor

### ISSUE THREAD

**Issue by jordyvandomselaar** [jakubfiala/atrament.js#12]
I can't really screenshot this, but wehen I'm scrolled up the line is right underneath my cursor, and when I scroll down the line is above my cursor.

Edit:
It only happens in device emulator mode.

**Comment by jakubfiala** [comment]
I think I know what this problem is – essentially, the `mousemove` event returns coordinates that aren't scaled properly. Which device emulator mode are you using? Is it Chrome's? It might be that it doesn't take into account the viewport meta tag, or it's just a bug. Let me know if this is critical to your project, but if not I'll close this, as I don't think it's a problem with the library.

**Comment by jordyvandomselaar** [comment]
I've find out that this also happens on actual mobile devices (ipad). Could you look into this?

**Comment by jakubfiala** [comment]
Ok, that's good to know. In that case, it may be a problem with handling the `changedTouches` [here.](https://github.com/jakubfiala/atrament.js/blob/master/src/atrament.js#L107) Sounds possible because I never tested on mobile with a scrolling canvas, only one that was `100vw, 100vh`. Will look into it.

**Comment by jordyvandomselaar** [comment]
Thanks man :D
