### ISSUE TITLE
Add new mode

### ISSUE THREAD

**Issue by ptkach** [jakubfiala/atrament.js#3]
Hi,

Thank you for very nice library. I'm really excited to use it in my project. 
Do you consider adding FILL as a third mode? I think it could be very useful

Thank,
Pavlo

**Comment by jakubfiala** [comment]
Hi Pavlo, thanks for the suggestion! How exactly do you imagine the fill mode to work? Would it be like *draw a path > path gets closed and filled* or more like the Photoshop paint bucket tool? 

Because the latter might be a bit too complex, as the lib would have to keep track of all the paths that exist on the canvas. Alternatively, it could perform some kind of a recursive algorithm to fill all the pixels that are the same colour in the clicked area, but that would also be quite computationally expensive. Definitely worth a try though!

**Comment by ptkach** [comment]
Thank you for reply. I was having in mind something more like Piant bucket fill works. 

Your idea with rec algo which fills pixels sounds more reasonable to me. Let me try to implement it and in case of successful result I will open PR

**Comment by jakubfiala** [comment]
cool, thanks a lot! It'll be interesting to see how it performs. This would be a great feature, as then people could make colouring books and stuff!

**Comment by jakubfiala** [comment]
This is fixed in #4 and available on `master` until v0.2.0 release. Closing now.
