### ISSUE TITLE
beginDrawing/stopDrawing do not record mouse positions

### ISSUE THREAD

**Issue by coranos** [jakubfiala/atrament.js#45]
https://github.com/jakubfiala/atrament.js/blob/59d3e6767b0b27e555c215e906993a616ea1d408/src/atrament.js#L151

**Comment by jakubfiala** [comment]
Hi @coranos - thanks for submitting this and #46. I will make it so the start/end positions are recorded, and also provided to strokestart/strokeend events

**Comment by coranos** [comment]
cool. if you are interested, here is my demo for 'undo'

https://coranos.github.io/bananos/sketch/

**Comment by jakubfiala** [comment]
Hey @coranos - this should now be fixed in [v1.1.0](https://github.com/jakubfiala/atrament.js/releases/tag/v.1.1.0). Feel free to reopen if you still encounter issues.

N.B. I decided to rename `begin/endDrawing` to `begin/endStroke` so the names are more descriptive of what the methods actually do.
