### ISSUE TITLE
Library should not add event listener on document

### ISSUE THREAD

**Issue by stmn** [jakubfiala/atrament.js#50]
I mean this:

> document.addEventListener('mouseup', mouseUp);

If something is happening outside of canvas (for example button clicking) it should not have any side effects for canvas, but it has currently. It's just a bad behaviour. Don't you agree?

**Comment by jakubfiala** [comment]
@stmn thanks for asking - unfortunately here it's necessary, because if your cursor leaves the canvas mid-stroke, and then you release the mouse button, the library needs to end the stroke. If it didn't, you could release the mouse, and when you moved over the canvas again, you'd still be drawing that one original stroke.

We could also use `mouseout`, but then every time you accidentally leave the canvas mid-stroke, you'd end the stroke even without releasing the mouse.

Hope that makes sense!
