### ISSUE TITLE
Realtime draw updates

### ISSUE THREAD

**Issue by profispojka** [jakubfiala/atrament.js#77]
strokerecorded event fires up only on mouseup. Is there an event that gives me real time draw data?

**Comment by profispojka** [comment]
Prepared a PR for this but i dont have permissions. Could you take a look? 
![image](https://user-images.githubusercontent.com/48156162/168347427-5000e78b-30aa-4042-b1d8-2b162c838288.png)

@jakubfiala

**Comment by jakubfiala** [comment]
Hello @profispojka - thank you for flagging this up, I think it sounds like a useful event to have. I think you can open the PR if you fork the repository, and then make a PR with this repository's `master` branch as the base :) I would also suggest calling the event `pointdrawn` - because at this point we haven't got a complete stroke. 

In any case, big thanks for your contribution! Once the PR is reviewed & merged, I'll release this in the v2.1.0 update

**Comment by profispojka** [comment]
Hi Jakub. PR is ready, please check it out. https://github.com/jakubfiala/atrament.js/pull/78

**Comment by jakubfiala** [comment]
addressed in the 3.0.0 release
